#  $Id: SConstruct 22 2010-01-15 16:00:22Z olivier.chaussavoine $ 
# import os
# dir_db = Dir('/home/olivier/sw/berkeleydb/db-4.7.25/build_unix')
dir_db = Dir('/home/olivier/sw/berkeleydb/db-4.8.30/build_unix')
dir_psql = Dir('/home/olivier/project/pgsql/src/include')
env = Environment(		CC='gcc -g ',
				LIBS=['m','db','pthread','readline'],#'xml2','readline'],
				LIBPATH =['/usr/lib',dir_db],
				CPPPATH=['.','#/include','/usr/include','',dir_db,dir_psql], #'/usr/include/libxml2','',dir_db],
				CPPDEFINES=['obCTESTCHEM'] #'obCSVNTEST', 'NDEBUG']
				)
env.Program('exemple_test',Split('exemple_test.c svn_test_main.c'))

prog_flux = Split('flux.c')
env.Program('flux_test',prog_flux + Split('flux_test.c svn_test_main.c'))
"""
prog_dbe = prog_flux+Split('dbe.c')
env.Program('dbe_test',prog_dbe + Split('dbe_test.c svn_test_main.c'))

prog_chemin = prog_dbe + Split('point.c chemin.c')
env.Program('chemin_test',prog_chemin+Split('chemin_test.c svn_test_main.c'))
"""
