#  $Id: SConstruct 22 2010-01-15 16:00:22Z olivier.chaussavoine $ 
# import os
# dir_db = Dir('/home/olivier/sw/berkeleydb/db-4.7.25/build_unix')
dir_db = Dir('/home/olivier/sw/berkeleydb/db-4.8.30/build_unix')
dir_psql = Dir('/home/olivier/project/pgsql/src/include')
env = Environment(		CC='gcc -g ',
				LIBS=['m','db','pthread','readline','svn_test'],#'xml2','readline'],
				LIBPATH =['/usr/lib',dir_db,'.'],
				CPPPATH=['.','#/include','/usr/include','',dir_db,dir_psql], #'/usr/include/libxml2','',dir_db],
				CPPDEFINES=['obCTEST']# CPPDEFINES=['obCTESTCHEM'] #'obCSVNTEST', 'NDEBUG']
				)
Library('svn_test',['svn_test_main.c','pg_test.c'])

# env.Program('exemple_test',Split('exemple_test.c'))

prog_flux = Split('flux.c')
env.Program('flux_test',prog_flux + Split('flux_test.c'))
env.Program('tbdb_test',prog_flux + Split('tbdb_test.c dbe.c iterators.c chemin.c'))

