#!/bin/bash
# AUTOMATISATION DES RELEASE
# **************************
# modifier VERSION-X,VERSION-Y,VERSION-Z
# cd openbarter
# ./doc/release-script 0.1.2 0.1.3 > ~/.bash/do-release_0.1.3
# chmod u+x ~/.bash/do-release_0.1.3
# do-release_0.1.3
#
#	chargement sur pgxn
#	https://manager.pgxn.org/upload
#	(olivierch,...)
#       upload the file ../release/openbarter-0.1.3

last="$1"
new="$2"
echo "sed 's,MODULE_VERSION,$new,g' META.json.in > META.json"
echo "soffice --invisible --norestore --convert-to pdf --outdir ./doc ./doc/*.odt"
echo "git commit -a -m 'preparation for v$new' "
echo "git tag -s v$new -m 'release v$new'"
dirnew="../release/openbarter-$new"
namenew="openbarter-$new"
echo "mkdir -p $dirnew"
echo "git archive --format=tar --prefix=$namenew/ v$new | gzip -9 > $dirnew/$namenew.tar.gz"
echo "# git archive --format zip --prefix=$namenew/ v$new --output $dirnew/$namenew.zip"
echo "cp doc/doc-ob.pdf $dirnew/$namenew-doc.pdf"
echo "git log --no-merges v$new ^v$last > $dirnew/ChangeLog-$new"
echo "git shortlog --no-merges v$new ^v$last > $dirnew/ShortLog-$new"
echo "git diff --stat --summary -M v$last v$new > $dirnew/diffstat-$new"
echo "git push --tags"
